### ISSUE TITLE
How to get the item index in show_vec?

### ISSUE THREAD

**Issue by imxood** [lucasmerlin/egui_dnd#10]
How to get the item index in show_vec?

**Comment by lucasmerlin** [comment]
It was not possible before. I've now added an index property to the state struct. Can you try and see if this works for you?

**Comment by imxood** [comment]
Thanks~ It's good, but it is the show's sorted item index, and also should add a index(raw data item)

when I want to delete the choosed item, I need the index(raw data item).

![image](https://github.com/lucasmerlin/egui_dnd/assets/14890680/c428fab2-1604-45fa-8794-19b1c0b18cf5)

![egui-pnp测试](https://github.com/lucasmerlin/egui_dnd/assets/14890680/75181298-e694-4ebc-817f-56c55da1e6f7)

**Comment by imxood** [comment]
It is good, thanks very much~
